---
name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Start deployment
        uses: bobheadxi/deployments@v0.6.0
        id: deployment
        with:
          step: start
          token: ${{ github.token }}
          env: pr_${{ github.event.number }}
          ref: ${{ github.head_ref }}


      - name: Checkout blog
        uses: actions/checkout@v2.3.4

      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: Cache pip
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pipenv
          key: ${{ runner.os }}-pip-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Checkout Pelican legacy plugins
        uses: actions/checkout@v2.3.4
        with:
          repository: getpelican/pelican-plugins
          path: plugins

      - name: Checkout Flex theme
        uses: actions/checkout@v2.3.4
        with:
          repository: alexandrevicenzi/Flex
          ref: v2.4.0
          path: themes/flex

      - name: Build blog
        run: |
          pelican content -o output -s publishconf.py --fatal warnings

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.5.11
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy
        run: aws s3 sync --only-show-errors --acl public-read --delete output/ s3://jml.io

      - name: Update deployment status
        if: always()
        uses: bobheadxi/deployments@v0.6.0
        with:
          step: finish
          token: ${{ github.token }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://jml.io/
